# Generated by Django 5.1.2 on 2025-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('diferencias', models.TextField(help_text='Diferencias con otras herramientas similares')),
                ('ejemplos', models.TextField(help_text='Ejemplos prácticos de uso')),
            ],
        ),
    ]
