# Generated by Django 5.1.2 on 2025-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientaia',
            name='categoria',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('codigo', 'Código')], max_length=50),
        ),
    ]
