# Generated by Django 5.2.4 on 2025-07-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_alter_herramientaia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientaia',
            name='nivel_educativo',
            field=models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('superior', 'Superior')], default=False, max_length=50),
            preserve_default=False,
        ),
    ]
