# Generated by Django 5.1.2 on 2025-07-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_herramientaia_nivel_educativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientaia',
            name='nivel_educativo',
            field=models.CharField(choices=[('escolar', 'Escolar'), ('universitario', 'Universitario'), ('tecnico', 'Técnico'), ('general', 'General')], max_length=50),
        ),
    ]
